name = "AudioSchedules"
uuid = "0990df78-ca1d-4d03-ab92-318744ee3999"
authors = ["Brandon Taylor <brandon.taylor221@gmail.com>"]
version = "0.0.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
SampledSignals = "bd7594eb-a658-542f-9e75-4c4d8908c167"

[compat]
DataStructures = "0.17"
SampledSignals = "2"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["Documenter", "Unitful"]
